force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Countries of the world</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Product Hierarchy</description>
    <inlineHelpText>Choose a Product Hierarchy</inlineHelpText>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products_del</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <description>The Product Hierarchy</description>
    <label>Product Hierarchy</label>
    <nameField>
        <label>Product Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductHierarchy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>states</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich country is the state</description>
    <inlineHelpText>choose a country</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>states</relationshipLabel>
    <relationshipName>states</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/Tax__c.object-meta.xml
<CustomObject>
    <description>Tax that will need to be payed</description>
    <label>Tax</label>
    <nameField>
        <label>Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Distribution Center</description>
    <inlineHelpText>Choose a Distribution Center in the list</inlineHelpText>
    <label>Distribution Center</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Texed Product</description>
    <inlineHelpText>Choose a product</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>State of the tax</description>
    <inlineHelpText>Choose a tax</inlineHelpText>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/TaxOnCost__c.field-meta.xml
<CustomField>
    <fullName>TaxOnCost__c</fullName>
    <description>Percentage of the text cost</description>
    <inlineHelpText>Write a percentage</inlineHelpText>
    <label>Tax on cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Tests/TaxTrigger/TaxTrigger_Test.cls
@isTest
private class TaxTrigger_Test {

    @TestSetup
    static void makeData(){
        
        Id pricebookId = TestFactorySObject.getStandardPricebookId();
        
        TestFactorySObject testFactory = TestFactorySObject.getInstance();
        
        ProductHierarchy__c productHierarchy = (ProductHierarchy__c) testFactory.createSObject(new ProductHierarchy__c());
        insert productHierarchy;

        Product2 productA = (Product2)testFactory.createSObject(new Product2(
            Name = 'Product A',
            ProductHierarchy__c = productHierarchy.Id
        ));
        insert productA;

        Product2 productB = (Product2) testFactory.createSObject(new Product2(
            Name = 'Product B',
            ProductHierarchy__c = productHierarchy.Id

        ));
        insert productB;
        
        Country__c countryA = (Country__c) testFactory.createSObject(
            new Country__c(
                Name = 'Country A'
            )
        );
        insert countryA;

        State__c stateA = (State__c) testFactory.createSObject(
            new State__c(
                Name = 'State A',
                Country__c = countryA.Id
            )
        );
        insert stateA;
        
        Country__c countryB = (Country__c) testFactory.createSObject(
            new Country__c(
                Name = 'Country B'
            )
        );
        insert countryB;

        State__c stateB = (State__c) testFactory.createSObject(
            new State__c(
                Name = 'State B',
                Country__c = countryB.Id
            )
        );
        insert stateB;
        
        DistributionCenter__c distributionCenterA = (DistributionCenter__c) testFactory.createSObject(
            new DistributionCenter__c(
                Name = 'Distribution Center A'
            )
        );
        insert distributionCenterA;

        Tax__c taxDefault = new Tax__c(
            Name = 'Tax Default',
            Product__c = productA.Id,
            State__c = stateA.id,
            TaxOnCost__c = 1,
            distributionCenter__c = distributionCenterA.Id
        );
        insert taxDefault;

    }

    @isTest
    static void testVerifyDuplicityFail() {

        Product2 productA = [SELECT Id FROM Product2 WHERE Name = 'Product A' LIMIT 1];
        State__c stateA = [SELECT Id FROM State__c WHERE Name = 'State A' LIMIT 1];
        DistributionCenter__c distributionCenterA = [SELECT Id FROM distributionCenter__c WHERE Name = 'Distribution Center A' LIMIT 1];

        Tax__c taxTest = new Tax__c(
            Name = 'Tax test',
            Product__c = productA.Id,
            State__c = stateA.Id,
            TaxOnCost__c = 1,
            distributionCenter__c = distributionCenterA.Id
        );

        Test.startTest();
            Database.SaveResult result = Database.insert(taxTest, false);
        Test.stopTest();

        Assert.areEqual(result.success, false, 'Test failed: Tax record was not inserted: '+ result.errors + '.');
    }

    @isTest
    static void testVerifyUpdateDuplicityPass() {

        Product2 productA = [SELECT Id FROM Product2 WHERE Name = 'Product A' LIMIT 1];
        Product2 productB = [SELECT Id FROM Product2 WHERE Name = 'Product B' LIMIT 1];
        State__c stateA = [SELECT Id FROM State__c WHERE Name = 'State A' LIMIT 1];
        State__c stateB = [SELECT Id FROM State__c WHERE Name = 'State B' LIMIT 1];
        DistributionCenter__c distributionCenterA = [SELECT Id FROM distributionCenter__c WHERE Name = 'Distribution Center A' LIMIT 1];

        Tax__c taxTest = new Tax__c(
            Name = 'Tax test',
            Product__c = productA.Id,
            State__c = stateB.Id,
            TaxOnCost__c = 1,
            distributionCenter__c = distributionCenterA.Id
        );
        insert taxTest;

        taxTest.Product__c = productB.Id;

        Test.startTest();
            Database.SaveResult result = Database.update(taxTest, false);
        Test.stopTest();

        Assert.areEqual(result.success, true, 'Test failed: Tax record was not inserted: '+ result.errors + '.');
    }
    @isTest
    static void testVerifyUpdateDuplicityFailed() {

        Product2 productA = [SELECT Id FROM Product2 WHERE Name = 'Product A' LIMIT 1];
        Product2 productB = [SELECT Id FROM Product2 WHERE Name = 'Product B' LIMIT 1];
        State__c stateA = [SELECT Id FROM State__c WHERE Name = 'State A' LIMIT 1];
        State__c stateB = [SELECT Id FROM State__c WHERE Name = 'State B' LIMIT 1];
        DistributionCenter__c distributionCenterA = [SELECT Id FROM distributionCenter__c WHERE Name = 'Distribution Center A' LIMIT 1];

        Tax__c taxTest = new Tax__c(
            Name = 'Tax test',
            Product__c = productA.Id,
            State__c = stateB.Id,
            TaxOnCost__c = 1,
            distributionCenter__c = distributionCenterA.Id
        );
        insert taxTest;

        taxTest.State__c = stateA.Id;

        Test.startTest();
            Database.SaveResult result = Database.update(taxTest, false);
        Test.stopTest();

        Assert.areEqual(result.success, false, 'Test failed: Tax record was not inserted: ' + result.errors + '.');
    }
}