force-app/main/default/objects/Order/fields/PaymentCondition__c.field-meta.xml
<CustomField>
    <fullName>PaymentCondition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich Payment Condition is iy</description>
    <inlineHelpText>Choose a Payment Condition</inlineHelpText>
    <label>Payment Condition</label>
    <referenceTo>Payment_Condition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentCondition__c/PaymentCondition__c.object-meta.xml
<CustomObject>
    <description>What is the Payment Condition</description>
    <label>Payment Condition</label>
    <nameField>
        <label>Payment Conditions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Batches/GoalItem/GoalsItemFillBasedOnOrderBatch.cls
global with sharing class GoalsItemFillBasedOnOrderBatch implements Database.Batchable<SObject>, Database.Stateful{

    Set<Id> seenIds = new Set<Id>();

    Map<Id, GoalItem__c> goalItems = new  Map<Id, GoalItem__c>();

    GoalItemOrderBatchService service = new GoalItemOrderBatchService();

    global Iterable<SObject> start(Database.BatchableContext bc){

        return Database.getQueryLocator([
            SELECT Id, OwnerId, Status, PaymentCondition__c
            FROM Order
            WHERE LastModifiedDate = THIS_YEAR
            Order by OwnerId
        ]);
        
    }

    global void execute(Database.BatchableContext bc, List<SObject > scope){

        Map<Id, GoalItem__c> updatedGoals = service.setGoalItems(goalItems, scope);

        goalItems.putAll(updatedGoals);
        
        seenIds.addAll(updatedGoals.keySet());

        if (!updatedGoals.isEmpty()) {

            Database.update(updatedGoals.values(), false);

        }

    }



   global void finish(Database.BatchableContext bc){

   }

}