force-app/main/default/objects/Product2/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Code of Product</description>
    <inlineHelpText>Write the code</inlineHelpText>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Product Hierarchy</description>
    <inlineHelpText>Choose a Product Hierarchy</inlineHelpText>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products_del</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductionCost__c.field-meta.xml
<CustomField>
    <fullName>ProductionCost__c</fullName>
    <description>The cost of production</description>
    <inlineHelpText>Write a price</inlineHelpText>
    <label>Production Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <description>The Product Hierarchy</description>
    <label>Product Hierarchy</label>
    <nameField>
        <label>Product Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductHierarchy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductHierarchy__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Write the Product Hierarchy</description>
    <inlineHelpText>Write the code</inlineHelpText>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Tests/ProductTrigger/ProductTrigger_Test.cls
@isTest
private class ProductTrigger_Test {

    @TestSetup
    static void makeData(){
        
        TestFactorySObject testFactory = TestFactorySObject.getInstance();

        ProductHierarchy__c productHierarchy = (ProductHierarchy__c) testFactory.createSObject(new ProductHierarchy__c());
        insert productHierarchy;
   
    }

    @isTest
    static void testCreatePricebookEntryTrigger() {
        
        Id pricebookId = TestFactorySObject.getStandardPricebookId();

        ProductHierarchy__c productHierarchy = [SELECT Id FROM ProductHierarchy__c LIMIT 1];

        Product2 product1 = new Product2(
            Name = 'Product 1',
            Code__c = 'Code',
            CurrencyIsoCode = 'BRL',
            IsActive = true,
            ProductionCost__c = 100,
            ProductHierarchy__c = productHierarchy.Id
        );

        Test.startTest();

        insert product1;

        PricebookEntry pricebookEntry = [
            SELECT Id
            FROM PricebookEntry 
            WHERE Product2Id = :product1.Id
            AND Pricebook2Id = :pricebookId
            LIMIT 1
        ];

        Test.stopTest();

        Assert.isNotNull(pricebookEntry, 'PricebookEntry was not created');

    }
   
    @isTest
    static void testUpdatePricebookEntryTrigger() {
        
        Id pricebookId = TestFactorySObject.getStandardPricebookId();

        ProductHierarchy__c productHierarchy = [SELECT Id FROM ProductHierarchy__c LIMIT 1];

        Product2 product1 = new Product2(
            Name = 'Product 1',
            Code__c = 'Code',
            CurrencyIsoCode = 'BRL',
            IsActive = true,
            ProductionCost__c = 100,
            ProductHierarchy__c = productHierarchy.Id
        );

        Test.startTest();

        insert product1;

        PricebookEntry pricebookEntry = [
            SELECT Id, UnitPrice
            FROM PricebookEntry 
            WHERE Product2Id = :product1.Id
            AND Pricebook2Id = :pricebookId
            LIMIT 1
        ];
        
        product1.ProductionCost__c = 200;
        update product1;

        PricebookEntry pricebookEntryUpdated = [
            SELECT Id, UnitPrice
            FROM PricebookEntry 
            WHERE Product2Id = :product1.Id
            AND Pricebook2Id = :pricebookId
            LIMIT 1
        ];

        Test.stopTest();

        Assert.areNotEqual(pricebookEntry.UnitPrice, pricebookEntryUpdated.UnitPrice, 'PricebookEntry was not updated');

    }
}