force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A group a Account</description>
    <inlineHelpText>Choose a account group</inlineHelpText>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City name</description>
    <inlineHelpText>Write the city`s name</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountAddress__c/AccountAddress__c.object-meta.xml
<CustomObject>
    <label>Account Address</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAddress__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich city is the Account Adress</description>
    <inlineHelpText>Choose a city</inlineHelpText>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipName>Account_Adresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>City</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich state is the city from</description>
    <inlineHelpText>Choose a state</inlineHelpText>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The contact&apos;s city</description>
    <inlineHelpText>Write the contact&apos;s city</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>The contact&apos;s state</description>
    <inlineHelpText>Choose the state on the piclist</inlineHelpText>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freight__c/Freight__c.object-meta.xml
<CustomObject>
    <description>Object intended for freight registration</description>
    <label>Freight Table</label>
    <nameField>
        <displayFormat>Freight-{0000}</displayFormat>
        <label>Freight Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freights table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich city is it from</description>
    <inlineHelpText>Choose a city</inlineHelpText>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Freights table</relationshipLabel>
    <relationshipName>Freights_table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Wich country is it from</description>
    <inlineHelpText>Choose a Country</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Freights table</relationshipLabel>
    <relationshipName>Freights_table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Freight Distribution Center</description>
    <inlineHelpText>Choose a Distribution Center</inlineHelpText>
    <label>Distribution Center</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Freights table</relationshipLabel>
    <relationshipName>Freights_table</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup for Product Hierarchy</description>
    <inlineHelpText>Choose a Product Hierarchy</inlineHelpText>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Freights table</relationshipLabel>
    <relationshipName>Freights_table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The state of it</description>
    <inlineHelpText>Choose a state</inlineHelpText>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Freights table</relationshipLabel>
    <relationshipName>Freights_table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/Margin__c.object-meta.xml
<CustomObject>
    <description>Object intended for registering margins</description>
    <label>Margin Table</label>
    <nameField>
        <label>Margim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Margins Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margin__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>city of margin</description>
    <inlineHelpText>choose a city</inlineHelpText>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Country of margin</description>
    <inlineHelpText>choose country</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Distribution center of margin</description>
    <inlineHelpText>Choose a distribution center</inlineHelpText>
    <label>Distribution Center</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product Hierarchy in magirn</description>
    <inlineHelpText>Choose a Product Hierarchy</inlineHelpText>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>State of the margin</description>
    <inlineHelpText>choose a margin state</inlineHelpText>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Distribution Center of the order</description>
    <inlineHelpText>Choose a Distribution Center</inlineHelpText>
    <label>Distribution Center</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Product Hierarchy</description>
    <inlineHelpText>Choose a Product Hierarchy</inlineHelpText>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products_del</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>states</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich country is the state</description>
    <inlineHelpText>choose a country</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>states</relationshipLabel>
    <relationshipName>states</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/Tax__c.object-meta.xml
<CustomObject>
    <description>Tax that will need to be payed</description>
    <label>Tax</label>
    <nameField>
        <label>Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Distribution Center</description>
    <inlineHelpText>Choose a Distribution Center in the list</inlineHelpText>
    <label>Distribution Center</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>State of the tax</description>
    <inlineHelpText>Choose a tax</inlineHelpText>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Tests/OrderInbound/OrderInbound_Test.cls
@isTest
private class OrderInbound_Test {
    @TestSetup
    static void makeData(){
        TestFactorySObject testFactory = TestFactorySObject.getInstance();
        
        Id pricebookId = TestFactorySObject.getStandardPricebookId();

        ProductHierarchy__c productHierarchy = (ProductHierarchy__c) testFactory.createSObject(new ProductHierarchy__c());
        insert productHierarchy;

        List<Product2> productList = new List<Product2>{
            (Product2) testFactory.createSObject(new Product2(
                Name = 'Product A',
                ExternalId__c = 'ascac',
                ProductHierarchy__c = productHierarchy.Id
                

            )),
            (Product2) testFactory.createSObject(new Product2(
                Name = 'Product B',
                ExternalId__c = 'asfda',
                ProductHierarchy__c = productHierarchy.Id

            ))
        };
        insert productList;
        
        List<Country__c> countryList = new List<Country__c>{
            (Country__c) testFactory.createSObject(
                new Country__c(
                    Name = 'Country A'
                )
            ),
            (Country__c) testFactory.createSObject(
                new Country__c(
                    Name = 'Country B'
                )
            )

        };

        insert countryList;

        List<State__c> stateList = new List<State__c>{
            (State__c) testFactory.createSObject(
                new State__c(
                    Name = 'State A',
                    Country__c = countryList[0].Id
                )
            ),
            (State__c) testFactory.createSObject(
                new State__c(
                    Name = 'State B',
                    Country__c = countryList[1].Id
                )
            )
        };

        insert stateList;

        List<City__c> cityList = new List<City__c>{
            (City__c) testFactory.createSObject(
                new City__c(
                    Name = 'City A',
                    State__c = stateList[0].Id
                )
            ),
            (City__c) testFactory.createSObject(
                new City__c(
                    Name = 'City B',
                    State__c = stateList[1].Id
                )
            )

        };

        insert cityList;
        
        DistributionCenter__c distributionCenterA = (DistributionCenter__c) testFactory.createSObject(
            new DistributionCenter__c(
                Name = 'Distribution Center A',
                ExternalId__c = '13131dsa'
            )
        );
        insert distributionCenterA;


        AccountGroup__c AccountGroupA = (AccountGroup__c) testFactory.createSObject(
            new AccountGroup__c()
        );
        insert AccountGroupA;

        Account AccountA = (Account) testFactory.createSObject(
            new Account(
                Name = 'Account A',
                ExternalId__c = 'asda1',
                AccountGroup__c = AccountGroupA.Id
        ));
        insert AccountA;

        Account AccountB = (Account) testFactory.createSObject(
            new Account(
                Name = 'Account B',
                ExternalId__c = 'wa2asfa',
                AccountGroup__c = AccountGroupA.Id
        ));
        insert AccountB;


        Margin__c MarginDefault = new Margin__c(
            Name = 'Margin Default',
            Product__c = productList[0].Id,
            State__c = stateList[0].id,
            Value__c = 1,
            distributionCenter__c = distributionCenterA.Id,
            Account__c = AccountA.Id
            
        );
        insert MarginDefault;


        Tax__c taxDefault = new Tax__c(
            Name = 'Tax Default',
            Product__c = productList[0].Id,
            State__c = stateList[0].id,
            TaxOnCost__c = 1,
            distributionCenter__c = distributionCenterA.Id
        );
        insert taxDefault;

        Freight__c FreightTest = new Freight__c(
            Name = 'Freight Test',
            Product__c = productList[0].Id,
            State__c = stateList[0].Id,
            Value__c = 1,
            distributionCenter__c = distributionCenterA.Id
            
        );
        insert FreightTest;

        Contract contractDefault = (Contract) testFactory.createSObject(
            new Contract(
                AccountId = AccountA.Id
            )
        );
        insert contractDefault;

        PaymentCondition__c paymentConditionDefault = (PaymentCondition__c) testFactory.createSObject(new PaymentCondition__c(
            ExternalId__c = '1'

        ));
        insert paymentConditionDefault;

        AccountAddress__c AccountAddressDefault = (AccountAddress__c) testFactory.createSObject(
            new AccountAddress__c(
                Account__c = AccountA.Id,
                City__c = cityList[0].Id,
                ExternalId__c = '1'

            )
        );
        insert AccountAddressDefault;

        Contact contactDefault = (Contact) testFactory.createSObject(new Contact());
        insert contactDefault;



    }


    @isTest
    static void inboundTest() {

        TestFactorySObject testFactory = TestFactorySObject.getInstance();

        Account accountDefault = [SELECT Id, ExternalId__c FROM Account WHERE Name = 'Account A' LIMIT 1];

        PaymentCondition__c paymentConditionDefault = [SELECT Id, ExternalId__c FROM PaymentCondition__c LIMIT 1];

        Product2 productA = [SELECT Id, ExternalId__c FROM Product2 WHERE Name = 'Product A' LIMIT 1];

        AccountAddress__c AccountAddressDefault = [SELECT Id, ExternalId__c FROM AccountAddress__c LIMIT 1];

        DistributionCenter__c distributionCenterA = [SELECT Id, ExternalId__c FROM DistributionCenter__c LIMIT 1];

        Wrappers.OrderItemWrapper orderItemWrapper = new Wrappers.OrderItemWrapper();
        orderItemWrapper.itemCode = 'Item A';
        orderItemWrapper.productCode = productA.ExternalId__c;
        orderItemWrapper.unitPrice = 1;
        orderItemWrapper.quantity = 1;
        orderItemWrapper.listPrice = 1;
        orderItemWrapper.orderCode = 'Order A';
        orderItemWrapper.totvsItem = true;

        Wrappers.OrderWrapper orderWrapper = new Wrappers.OrderWrapper();
        orderWrapper.orderCode = 'Order A';
        orderWrapper.orderItems = new List<Wrappers.OrderItemWrapper>();
        orderWrapper.orderItems.add(orderItemWrapper);
        orderWrapper.accountCode = accountDefault.ExternalId__c;
        orderWrapper.paymentCode = paymentConditionDefault.ExternalId__c;
        orderWrapper.distributionCenterCode = distributionCenterA.ExternalId__c;
        orderWrapper.addressCode = AccountAddressDefault.ExternalId__c;
        orderWrapper.freightType = 'Cif';
        orderWrapper.obs = 'Test';
        orderWrapper.status = 'New';
        orderWrapper.effectiveDate = Date.today();
        orderWrapper.deliveryDate = Date.today();

        System.debug('Order: ' + orderWrapper);

        List<Wrappers.OrderWrapper> ordersWrapper = new List<Wrappers.OrderWrapper>();
        ordersWrapper.add(orderWrapper);

        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = '/services/apexrest/orders/';
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');

        String jsonBody = JSON.serialize(new Map<String, List<Wrappers.OrderWrapper>>{
            'request' => ordersWrapper
        });

        System.debug('Body: ' + jsonBody);

        request.requestBody = Blob.valueOf(jsonBody);

        RestContext.request = request;
        RestContext.response = response;

        Test.startTest();
            List<InResponse> responseList = OrderInbound.createOrder();
        Test.stopTest();

        System.debug('Responta: ' + responseList);

        System.Assert.areEqual(false, responseList[0].hasError , 'Deveria ter retornado uma resposta sem erros');
        

    }
}