force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A group a Account</description>
    <inlineHelpText>Choose a account group</inlineHelpText>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountGroup__c/AccountGroup__c.object-meta.xml
<CustomObject>
    <label>Account Group</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Countries of the world</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margin__c/Margin__c.object-meta.xml
<CustomObject>
    <description>Object intended for registering margins</description>
    <label>Margin Table</label>
    <nameField>
        <label>Margim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Margins Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margin__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account of the margin</description>
    <inlineHelpText>choose a account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>group op account</description>
    <inlineHelpText>choose a Account Group</inlineHelpText>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Country of margin</description>
    <inlineHelpText>choose country</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Distribution center of margin</description>
    <inlineHelpText>Choose a distribution center</inlineHelpText>
    <label>Distribution Center</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product of margin table</description>
    <inlineHelpText>choose a product</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product Hierarchy in magirn</description>
    <inlineHelpText>Choose a Product Hierarchy</inlineHelpText>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>State of the margin</description>
    <inlineHelpText>choose a margin state</inlineHelpText>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>how much is the margin</description>
    <inlineHelpText>Write a percentage value</inlineHelpText>
    <label>Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Product Hierarchy</description>
    <inlineHelpText>Choose a Product Hierarchy</inlineHelpText>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products_del</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <description>The Product Hierarchy</description>
    <label>Product Hierarchy</label>
    <nameField>
        <label>Product Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductHierarchy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>states</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich country is the state</description>
    <inlineHelpText>choose a country</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>states</relationshipLabel>
    <relationshipName>states</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Tests/MarginTrigger/MarginTrigger_Test.cls
@isTest
private class MarginTrigger_Test {

    @TestSetup
    static void makeData(){
        
        Id pricebookId = TestFactorySObject.getStandardPricebookId();
        
        TestFactorySObject testFactory = TestFactorySObject.getInstance();
        
        ProductHierarchy__c productHierarchy = (ProductHierarchy__c) testFactory.createSObject(new ProductHierarchy__c());
        insert productHierarchy;

        Product2 productA = (Product2)testFactory.createSObject(new Product2(
            Name = 'Product A',
            ProductHierarchy__c = productHierarchy.Id
        ));
        insert productA;

        Product2 productB = (Product2) testFactory.createSObject(new Product2(
            Name = 'Product B',
            ProductHierarchy__c = productHierarchy.Id

        ));
        insert productB;
        
        Country__c countryA = (Country__c) testFactory.createSObject(
            new Country__c(
                Name = 'Country A'
            )
        );
        insert countryA;

        State__c stateA = (State__c) testFactory.createSObject(
            new State__c(
                Name = 'State A',
                Country__c = countryA.Id
            )
        );
        insert stateA;
        
        Country__c countryB = (Country__c) testFactory.createSObject(
            new Country__c(
                Name = 'Country B'
            )
        );
        insert countryB;

        State__c stateB = (State__c) testFactory.createSObject(
            new State__c(
                Name = 'State B',
                Country__c = countryB.Id
            )
        );
        insert stateB;
        
        DistributionCenter__c distributionCenterA = (DistributionCenter__c) testFactory.createSObject(
            new DistributionCenter__c(
                Name = 'Distribution Center A'
            )
        );
        insert distributionCenterA;


        AccountGroup__c AccountGroupA = (AccountGroup__c) testFactory.createSObject(
            new AccountGroup__c()
        );
        insert AccountGroupA;

        Account AccountA = (Account) testFactory.createSObject(
            new Account(
                Name = 'Account A',
                AccountGroup__c = AccountGroupA.Id
        ));
        insert AccountA;


        Margin__c MarginDefault = new Margin__c(
            Name = 'Margin Default',
            Product__c = productA.Id,
            State__c = stateA.id,
            Value__c = 1,
            distributionCenter__c = distributionCenterA.Id,
            Account__c = AccountA.Id
            
        );
        insert MarginDefault;

    }

    @isTest
    static void testVerifyDuplicityPass() {

        Product2 productA = [SELECT Id FROM Product2 WHERE Name = 'Product A' LIMIT 1];
        State__c stateB = [SELECT Id FROM State__c WHERE Name = 'State B' LIMIT 1];
        DistributionCenter__c distributionCenterA = [SELECT Id FROM distributionCenter__c WHERE Name = 'Distribution Center A' LIMIT 1];
        Account AccountA = [SELECT Id FROM Account WHERE Name = 'Account A' LIMIT 1];

        Margin__c MarginTest = new Margin__c(
            Name = 'Margin Test',
            Product__c = productA.Id,
            State__c = stateB.Id,
            Value__c = 1,
            distributionCenter__c = distributionCenterA.Id,
            Account__c = AccountA.Id
            
        );

        Test.startTest();
            Database.SaveResult result = Database.insert(MarginTest, false);
        Test.stopTest();

        Assert.areEqual(result.success, true, 'Test failed: Margin record was not inserted: '+ result.errors + '.');
    }

    @isTest
    static void testVerifyDuplicityFail() {

        Product2 productA = [SELECT Id FROM Product2 WHERE Name = 'Product A' LIMIT 1];
        State__c stateA = [SELECT Id FROM State__c WHERE Name = 'State A' LIMIT 1];
        DistributionCenter__c distributionCenterA = [SELECT Id FROM distributionCenter__c WHERE Name = 'Distribution Center A' LIMIT 1];
        Account AccountA = [SELECT Id FROM Account WHERE Name = 'Account A' LIMIT 1];

        Margin__c MarginTest = new Margin__c(
            Name = 'Margin Test',
            Product__c = productA.Id,
            State__c = stateA.Id,
            Value__c = 1,
            distributionCenter__c = distributionCenterA.Id,
            Account__c = AccountA.Id

            
        );

        Test.startTest();
            Database.SaveResult result = Database.insert(MarginTest, false);
        Test.stopTest();

        Assert.areEqual(result.success, false, 'Test failed: Margin record was inserted: '+ result.errors + '.');
    }

    @isTest
    static void testVerifyUpdateDuplicityPass() {

        Product2 productA = [SELECT Id FROM Product2 WHERE Name = 'Product A' LIMIT 1];
        Product2 productB = [SELECT Id FROM Product2 WHERE Name = 'Product B' LIMIT 1];
        State__c stateA = [SELECT Id FROM State__c WHERE Name = 'State A' LIMIT 1];
        State__c stateB = [SELECT Id FROM State__c WHERE Name = 'State B' LIMIT 1];
        DistributionCenter__c distributionCenterA = [SELECT Id FROM distributionCenter__c WHERE Name = 'Distribution Center A' LIMIT 1];
        Account AccountA = [SELECT Id FROM Account WHERE Name = 'Account A' LIMIT 1];

        Margin__c MarginTest = new Margin__c(
            Name = 'Margin Test',
            Product__c = productA.Id,
            State__c = stateB.Id,
            Value__c = 1,
            distributionCenter__c = distributionCenterA.Id,
            Account__c = AccountA.Id

            
        );
        insert MarginTest;

        MarginTest.Product__c = productB.Id;

        Test.startTest();
            Database.SaveResult result = Database.update(MarginTest, false);
        Test.stopTest();

        Assert.areEqual(result.success, true, 'Test failed: Margin record was not updated: '+ result.errors + '.');
    }
    
    @isTest
    static void testVerifyUpdateDuplicityFailed() {

        Product2 productA = [SELECT Id FROM Product2 WHERE Name = 'Product A' LIMIT 1];
        Product2 productB = [SELECT Id FROM Product2 WHERE Name = 'Product B' LIMIT 1];
        State__c stateA = [SELECT Id FROM State__c WHERE Name = 'State A' LIMIT 1];
        State__c stateB = [SELECT Id FROM State__c WHERE Name = 'State B' LIMIT 1];
        DistributionCenter__c distributionCenterA = [SELECT Id FROM distributionCenter__c WHERE Name = 'Distribution Center A' LIMIT 1];
        Account AccountA = [SELECT Id FROM Account WHERE Name = 'Account A' LIMIT 1];

        Margin__c MarginTest = new Margin__c(
            Name = 'Margin Test',
            Product__c = productA.Id,
            State__c = stateB.Id,
            Value__c = 1,
            distributionCenter__c = distributionCenterA.Id,
            Account__c = AccountA.Id
            
        );
        insert MarginTest;

        MarginTest.State__c = stateA.Id;

        Test.startTest();
            Database.SaveResult result = Database.update(MarginTest, false);
        Test.stopTest();

        Assert.areEqual(result.success, false, 'Test failed: Margin record was updated: ' + result.errors + '.');
    }

    @isTest
    static void testVerifyDuplicitySameBatch(){

        Product2 productA = [SELECT Id FROM Product2 WHERE Name = 'Product A' LIMIT 1];
        Product2 productB = [SELECT Id FROM Product2 WHERE Name = 'Product B' LIMIT 1];
        State__c stateA = [SELECT Id FROM State__c WHERE Name = 'State A' LIMIT 1];
        State__c stateB = [SELECT Id FROM State__c WHERE Name = 'State B' LIMIT 1];
        DistributionCenter__c distributionCenterA = [SELECT Id FROM distributionCenter__c WHERE Name = 'Distribution Center A' LIMIT 1];
        Account AccountA = [SELECT Id FROM Account WHERE Name = 'Account A' LIMIT 1];

        List<Margin__c> MarginTestList = new List<Margin__c>{
            new Margin__c(
                Name = 'Margin Test',
                Product__c = productA.Id,
                State__c = stateB.Id,
                Value__c = 1,
                distributionCenter__c = distributionCenterA.Id,
                Account__c = AccountA.Id

            ),
            new Margin__c(
                Name = 'Margin Test 2',
                Product__c = productA.Id,
                State__c = stateB.Id,
                Value__c = 1,
                distributionCenter__c = distributionCenterA.Id,
                Account__c = AccountA.Id

            )
        };

    Test.startTest();
            Database.SaveResult[] results = Database.insert(MarginTestList, false);

        Test.stopTest();

        Boolean hasFailed = false;
        
        for(Database.SaveResult res : results){
            if(!res.success){
                hasFailed = true;
                break;
            }
        }   

        Assert.areEqual(hasFailed, true, 'Program should not allow insersion of duplicated records in same batch');
        
    }

    @isTest
    static void testTriggerEnabled(){
        
        MarginTriggerHandler.disableTrigger();
        MarginTriggerHandler.enableTrigger();

        Assert.areEqual(true, MarginTriggerHandler.isTriggerEnabled(), 'Trigger should be enabled');

    }
    
}