force-app/main/default/objects/ApiLog__c/ApiLog__c.object-meta.xml
<CustomObject>
    <label>Api Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Api Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApiLog__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Original Object Endpoint</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApiLog__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <description>Where is the request From</description>
    <label>From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SALESFORCE</fullName>
            </value>
            <value>
                <fullName>TOTVS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApiLog__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>requestBody</description>
    <label>Request</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/endpoint/Log/LogEndpoint.cls
@RestResource(urlMapping='/Log/*')
global with sharing class LogEndpoint {


    @httpGet
    global static void getLastLog(){
        
        RestRequest request = RestContext.request;

        RestResponse response = RestContext.response;

        ApiLog__c log = [   
            SELECT Id, Request__c, Response__c, Endpoint__c, From__c, CreatedDate
            FROM  ApiLog__c
            WHERE Endpoint__c = 'Order'
            ORDER BY CreatedDate DESC
            LIMIT 1    
        ];

        
        Map<String, Object> responseBody = new Map<String, Object>();

        responseBody.put('Id', log.Id);
        responseBody.put('Request', log.Request__c);
        responseBody.put('Response', log.Response__c);
        responseBody.put('Endpoint', log.Endpoint__c);
        responseBody.put('From', log.From__c);
        responseBody.put('status', 'success');

        response.statusCode = 200;
        response.addHeader('Content-Type', 'application/json');

        response.responseBody = Blob.valueOf(JSON.serializePretty(responseBody));


        

    }

}