force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>City</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich state is the city from</description>
    <inlineHelpText>Choose a state</inlineHelpText>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Countries of the world</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <description>The Product Hierarchy</description>
    <label>Product Hierarchy</label>
    <nameField>
        <label>Product Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductHierarchy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>states</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich country is the state</description>
    <inlineHelpText>choose a country</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>states</relationshipLabel>
    <relationshipName>states</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Utils/MakeKeys.cls
public with sharing class MakeKeys {
    private static Set<String> fields = new Set<String>{
        'City__c',
        'State__c',
        'Country__c',
        'Product__c',
        'ProductHierarchy__c',
        'Account__c',
        'AccountHierarchy__c'
    };

    public static String makeKey(SObject record){
        
        String key = '';

        Map<String,Object> fieldaMap = record.getPopulatedFieldsAsMap();

        for(String iString : fields){

            string value = String.valueOf(fieldaMap.get(iString));

            if(fields.contains(iString)){

                key += (value == null) ? '' : (value + '-');

            }
            

        }
        
        if(key.endsWith('-')){

            key = key.substring(0, key.length() - 1);

        }

        return key;
    }

    public static Map<String,Id> makeKeyMap(List<SObject> records){

        Map<String,Id> keyMap = new Map<String,Id>();
        
        for(SObject iRecord : records){
        
            keyMap.put(makeKey(iRecord), iRecord.Id);
        
        }
        
        return keyMap;
    }


}