force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>City</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich state is the city from</description>
    <inlineHelpText>Choose a state</inlineHelpText>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Countries of the world</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margin__c/Margin__c.object-meta.xml
<CustomObject>
    <description>Object intended for registering margins</description>
    <label>Margin Table</label>
    <nameField>
        <label>Margim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Margins Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margin__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>city of margin</description>
    <inlineHelpText>choose a city</inlineHelpText>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Country of margin</description>
    <inlineHelpText>choose country</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product of margin table</description>
    <inlineHelpText>choose a product</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product Hierarchy in magirn</description>
    <inlineHelpText>Choose a Product Hierarchy</inlineHelpText>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>State of the margin</description>
    <inlineHelpText>choose a margin state</inlineHelpText>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Margins Table</relationshipLabel>
    <relationshipName>Margins_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <description>The Product Hierarchy</description>
    <label>Product Hierarchy</label>
    <nameField>
        <label>Product Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductHierarchy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>states</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Wich country is the state</description>
    <inlineHelpText>choose a country</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>states</relationshipLabel>
    <relationshipName>states</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Margin/MarginTriggerHelper.cls
public with sharing class MarginTriggerHelper {
    public static void HandleInsertMargin(List<Margin__c> newList){
        VerifyDuplicity(newList);

    }

    public static void HandleUpdateMargin(List<Margin__c> oldList, List<Margin__c> newList){
        VerifyDuplicity(newList);
    }

    private static void VerifyDuplicity(List<Margin__c> records){
        Set<String> keys = new Set<String>();
        Set<Id> productIds = new Set<Id>();
        Set<Id> productHierarchyIds = new Set<Id>();

        for(Margin__c iMargin : records){

            String temp = MakeKey(iMargin);
            if(keys.contains(temp))iMargin.addError('Duplicate in batch');
            else keys.add(temp);
            
   

            if(iMargin.Product__c != null) productIds.add(iMargin.Product__c);
            if(iMargin.ProductHierarchy__c != null) productHierarchyIds.add(iMargin.ProductHierarchy__c);

        }
        
        List<Margin__c> MarginList = [select Id, Product__c, ProductHierarchy__c, City__c, State__c, Country__c 
                                    from Margin__c
                                    where ProductHierarchy__c in :productHierarchyIds
                                    and Product__c in :productIds
                                ];

        Map<String, Margin__c> marginMap = new Map<String, Margin__c>();

        for(Margin__c iMargin : MarginList){
            marginMap.put(MakeKey(iMargin), iMargin);
        }

        for(Margin__c iMargin : records){
            if(marginMap.containsKey(MakeKey(iMargin))){
                iMargin.addError('Margin already exists');
            }
        }



    }



    private static String MakeKey(Margin__c margin){
        return String.valueOf(margin.Product__c) + '-' +
               String.valueOf(margin.ProductHierarchy__c) + '-' +
               String.valueOf(margin.City__c) + '-' +
               String.valueOf(margin.State__c) + '-' +
               String.valueOf(margin.Country__c);
    }

}